spring:
  application:
    name: @project.artifactId@
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liumapp/simple-docker-demo/
          search-paths: config

server:
  port: 7001

eureka:
  client:
    service-url:
      defaultZone: http://192.168.2.2:1234/eureka/

