spring:
  application:
    name: @project.artifactId@

server:
  port: 2333

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:1234/eureka/
zuul:
  routes:
    docker-weba:
      serviceId: docker-weba
      path: /**
    docker-webb:
      serviceId: docker-webb
      path: /**


