spring:
  application:
    name: docker-gateway

server:
  port: 2333

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1234/eureka/
zuul:
  routes:
    docker-weba:
      serviceId: docker-weba
      path: /**
    docker-webb:
      serviceId: docker-webb
      path: /**


